# Dados absolutos e relativos

In [25]:
# %pip install pandas
import pandas as pd

## Percentuais

In [26]:
dados = {'emprego': ['Adm_banco_de_dados', 'Programador', 'Arquiteto_de_Redes'],
         'nova_jersey': [97350, 82080, 112840],
         'florida': [77140, 71540, 62310]
         }

dados

{'emprego': ['Adm_banco_de_dados', 'Programador', 'Arquiteto_de_Redes'],
 'nova_jersey': [97350, 82080, 112840],
 'florida': [77140, 71540, 62310]}

In [52]:
dataset = pd.DataFrame(dados)
dataset

              emprego  nova_jersey  florida
0  Adm_banco_de_dados        97350    77140
1         Programador        82080    71540
2  Arquiteto_de_Redes       112840    62310

In [28]:
dataset['nova_jersey'].sum()

np.int64(292270)

In [29]:
dataset['florida'].sum()

np.int64(210990)

In [30]:
dataset['nova_jersey_%'] = (dataset['nova_jersey'] / dataset['nova_jersey'].sum()) * 100
dataset['florida_%'] = (dataset['florida'] / dataset['florida'].sum()) * 100

In [31]:
dataset

              emprego  nova_jersey  florida  nova_jersey_%  florida_%
0  Adm_banco_de_dados        97350    77140      33.308242  36.560974
1         Programador        82080    71540      28.083621  33.906820
2  Arquiteto_de_Redes       112840    62310      38.608136  29.532205

## Exercicios Percentuais

In [178]:
census = pd.read_csv('../Bases de dados/census.csv')

In [179]:
census = census[['education', 'income']]

In [183]:
rendas = census.groupby(['education', 'income'])['education'].count()

rendas

education     income
10th          <=50K      871
              >50K        62
11th          <=50K     1115
              >50K        60
12th          <=50K      400
              >50K        33
1st-4th       <=50K      162
              >50K         6
5th-6th       <=50K      317
              >50K        16
7th-8th       <=50K      606
              >50K        40
9th           <=50K      487
              >50K        27
Assoc-acdm    <=50K      802
              >50K       265
Assoc-voc     <=50K     1021
              >50K       361
Bachelors     <=50K     3134
              >50K      2221
Doctorate     <=50K      107
              >50K       306
HS-grad       <=50K     8826
              >50K      1675
Masters       <=50K      764
              >50K       959
Preschool     <=50K       51
Prof-school   <=50K      153
              >50K       423
Some-college  <=50K     5904
              >50K      1387
Name: education, dtype: int64

In [184]:
rendas.index

MultiIndex([(        ' 10th', ' <=50K'),
            (        ' 10th',  ' >50K'),
            (        ' 11th', ' <=50K'),
            (        ' 11th',  ' >50K'),
            (        ' 12th', ' <=50K'),
            (        ' 12th',  ' >50K'),
            (     ' 1st-4th', ' <=50K'),
            (     ' 1st-4th',  ' >50K'),
            (     ' 5th-6th', ' <=50K'),
            (     ' 5th-6th',  ' >50K'),
            (     ' 7th-8th', ' <=50K'),
            (     ' 7th-8th',  ' >50K'),
            (         ' 9th', ' <=50K'),
            (         ' 9th',  ' >50K'),
            (  ' Assoc-acdm', ' <=50K'),
            (  ' Assoc-acdm',  ' >50K'),
            (   ' Assoc-voc', ' <=50K'),
            (   ' Assoc-voc',  ' >50K'),
            (   ' Bachelors', ' <=50K'),
            (   ' Bachelors',  ' >50K'),
            (   ' Doctorate', ' <=50K'),
            (   ' Doctorate',  ' >50K'),
            (     ' HS-grad', ' <=50K'),
            (     ' HS-grad',  ' >50K'),
            (     ' Masters', ' <=50K'),
            (     ' Masters',  ' >50K'),
            (   ' Preschool', ' <=50K'),
            ( ' Prof-school', ' <=50K'),
            ( ' Prof-school',  ' >50K'),
            (' Some-college', ' <=50K'),
            (' Some-college',  ' >50K')],
           names=['education', 'income'])

In [186]:
rendas[' Bachelors', ' <=50K'], rendas[' Bachelors', ' >50K']

(np.int64(3134), np.int64(2221))

In [ ]:
total = int(rendas[' Bachelors', ' >50K']) + int(rendas[' Bachelors', ' <=50K'])

In [199]:
dados = {'salario': ['>50K', '<=50K'],
         '_%_': [(rendas[' Bachelors', ' >50K'] / total) * 100, (rendas[' Bachelors', ' <=50K'] / total) * 100]
         }

result = pd.DataFrame(dados)
result

  salario        _%_
0    >50K  41.475257
1   <=50K  58.524743

## Exercicios coeficientes e taxas